from fastmcp import Context

from handlers.config_rendering import handle_get_rendered_config


def register(mcp):

    @mcp.tool()
    async def get_rendered_config(
        blueprint_id: str,
        system_id: str,
        sections: list[str] | None = None,
        subsections: dict[str, list[str]] | None = None,
        instance_name: str | None = None,
        ctx: Context = None,
    ) -> dict:
        """
        Returns the rendered JunOS (or EOS) device configuration for a
        specific switch as generated by Apstra from its intent model.

        The raw config string is parsed into its root-level JunOS hierarchical
        sections (e.g. system, interfaces, routing-options, protocols,
        policy-options). The response always includes available_subsections,
        which lists the first-level child block names within each returned
        section — use these to make a targeted follow-up call via the
        subsections parameter.

        The config is split at the '------BEGIN SECTION CONFIGLETS------'
        boundary. Sections before the boundary are AOS-managed config.
        Sections after it come from user-defined configlets applied to the
        device. Both sets are returned separately so the origin of each config
        block is unambiguous.

        Call this tool to:
          - Review the exact config Apstra would push to a device
          - Compare rendered config against expected design intent
          - Inspect routing policy, BGP groups, prefix-lists, and communities
          - Examine rendered configlet output alongside AOS config
          - Diagnose differences between what's intended and what's deployed
          - Answer questions like "what communities are set on Spine2?"

        Recommended two-step workflow to minimise context:
          1. Call with sections=["interfaces"] (or whichever root sections
             you need). The response includes available_subsections, listing
             child names such as interface names or BGP group block names.
          2. Call again with subsections={"interfaces": ["ge-0/0/0"]} to
             receive only that child block in subsection_detail.

        Data source: live network (live_data_client). Results reflect the
        current committed design intent.

        Use get_blueprints to discover valid blueprint_id values.
        Use get_systems to discover valid system_id values — use the
        `system_id` field (hardware serial, e.g. "5254002D005F"), NOT the
        `id` field (graph node ID).

        Args:
            blueprint_id:   The Apstra blueprint ID.
            system_id:      Hardware serial of the target switch (e.g.
                            "5254002D005F"). Use the `system_id` field from
                            get_systems output — NOT the `id` field.
            sections:       Optional list of root section names to include.
                            Use names from available_sections.
                            Omit or pass null to return all root sections.
                            Examples: ["routing-options", "protocols"],
                            ["policy-options"], ["system", "interfaces"]
            subsections:    Optional dict mapping root section name to a list
                            of child block names to extract from within it.
                            When provided for a section, that section is
                            removed from 'sections' and only the requested
                            child blocks appear in 'subsection_detail'.
                            Child names are taken from available_subsections.
                            Examples:
                              {"interfaces": ["ge-0/0/0", "lo0"]}
                              {"protocols": ["bgp", "lldp"]}
                              {"policy-options": ["policy-statement bgp-aos-policy"]}
                              {"interfaces": ["ge-0/0/0"], "protocols": ["bgp"]}
            instance_name:  Optional. The Apstra instance name (from
                            instances.yaml). If omitted, all instances are
                            queried and results are merged.

        Returns:
            instance:                     Apstra instance name
            blueprint_id:                 Blueprint queried
            system_id:                    System hardware serial queried
            available_sections:           All section names in the AOS config
            available_configlet_sections: All section names in the configlet
                                          config
            available_subsections:        Dict of {section_name: [child_names]}
                                          for each returned root section.
                                          Use these names in the subsections
                                          parameter to narrow further.
            sections:                     Dict of {name: full_block_text} for
                                          root sections NOT narrowed via the
                                          subsections parameter.
            subsection_detail:            Dict of {section_name: {child_name:
                                          block_text}} for sections narrowed
                                          via the subsections parameter. Empty
                                          if subsections was not provided.
            configlets:                   Dict of {name: full_block_text} for
                                          the configlet config.

        Common root section names (vary by device role and Apstra design):
            system          — hostname, NTP, syslog, SNMP (scalar device config)
            interfaces      — physical interface and logical unit config
            routing-options — router-id, AS number, forwarding table, ECMP,
                              graceful-restart, static routes
            protocols       — BGP groups and neighbours (l3clos-s, l3clos-s-evpn,
                              l3clos-l), LLDP, RSTP, OSPF
            policy-options  — community strings, policy statements, prefix-lists
                              (AllPodNetworks, BGP-AOS-Policy, PFE-LB, etc.)
            firewall        — filter-based forwarding, firewall filters (leaves)
            vlans           — VLAN definitions (VLAN-mode or hybrid devices)
            bridge-domains  — L2 bridge domain config (IRB devices)

        Common available_subsections child names (examples):
            interfaces       → ge-0/0/0, ge-0/0/1, xe-0/0/0, lo0, irb, em0
            protocols        → bgp, lldp, rstp, ospf, sflow
            protocols > bgp  → use subsections={"protocols": ["bgp"]} to get the
                               full bgp block, which contains l3clos-s, l3clos-s-evpn,
                               and l3clos-l groups as nested stanzas
            policy-options   → community <name>, policy-statement <name>
                               e.g. "community default_direct_v4",
                                    "policy-statement bgp-aos-policy"
        """
        return await handle_get_rendered_config(
            ctx.lifespan_context["sessions"],
            blueprint_id,
            system_id,
            sections,
            subsections,
            instance_name,
        )
