from typing import Annotated

from fastmcp import Context
from pydantic import Field

from handlers.config_rendering import handle_get_rendered_config


def register(mcp):

    @mcp.tool()
    async def get_rendered_config(
        blueprint_id: Annotated[
            str,
            Field(description=(
                "Required. Apstra blueprint ID or partial label (e.g. 'DC1'). "
                "Use get_blueprints to list available blueprints and their IDs. "
                "Pass a full UUID for a specific blueprint."
            )),
        ],
        system_id: Annotated[
            str,
            Field(description=(
                "Hardware chassis serial of the target switch (e.g. '5254002D005F'). "
                "Use the system_id field from get_systems — NOT the id field."
            )),
        ],
        sections: Annotated[
            list[str] | None,
            Field(default=None, description=(
                "Root JunOS config sections to return (e.g. ['interfaces', 'protocols']). "
                "Omit to return all sections. "
                "Common sections: system, interfaces, routing-options, protocols, "
                "policy-options, firewall, vlans, bridge-domains."
            )),
        ] = None,
        subsections: Annotated[
            dict[str, list[str]] | None,
            Field(default=None, description=(
                "Narrow one or more sections to specific child blocks. "
                "Keys are root section names; values are lists of child names from available_subsections. "
                "E.g. {'interfaces': ['ge-0/0/0', 'lo0'], 'protocols': ['bgp']}. "
                "Sections listed here appear in subsection_detail rather than sections."
            )),
        ] = None,
        instance_name: Annotated[
            str | None,
            Field(default=None, description="Apstra instance name. Do not ask the user — leave as None to query all instances. Only set if the user explicitly names a specific instance."),
        ] = None,
        ctx: Context = None,
    ) -> dict:
        """
        Return the rendered JunOS device configuration for a switch as generated by Apstra from its intent model.

        The config is parsed into hierarchical root sections (interfaces, protocols, policy-options, etc.)
        for easy filtering. Use sections to limit which root blocks are returned. Use subsections for
        surgical extraction of a specific interface or BGP group without fetching the full section.

        Recommended two-step workflow to minimise context size:
          1. Call with sections=["interfaces"] (or whichever section you need). The response includes
             available_subsections listing child names (interface names, BGP group names, etc.).
          2. Call again with subsections={"interfaces": ["ge-0/0/0"]} to get just that child block.

        The config is split at '------BEGIN SECTION CONFIGLETS------': AOS-managed config is in
        sections/subsection_detail; configlet-sourced config is in configlets.

        Returns: available_sections, available_configlet_sections, available_subsections
        (dict of child names per section), sections (dict of root block text), subsection_detail
        (dict of child block text when subsections param used), configlets.
        Data source: live Apstra API (reflects current committed design intent).
        """
        return await handle_get_rendered_config(
            ctx.lifespan_context["sessions"],
            blueprint_id,
            system_id,
            sections,
            subsections,
            instance_name,
        )
